sudo: false
language: node_js
node_js:
- '7'
- '8'
before_deploy:
- npm run build
deploy:
  provider: npm
  email: kevin@onelittlerobot.co.uk
  api_key:
    secure: T+/ooMJl0bsnMXAE9eaAMuXxHTdZpsuwQvPQ1D9HMuLYYfBR+tTDVJQ2p+mvQHUepYbGE8KFc5GEnzUevJgiAzQWmQcmebNywZWCYZRDvRav5WEL08hfilF1zht4+DSiBuLoHrZ+UaoodF/G0bYa6hq+SeWQWZZV6ih23zzExjmLOZhia2FhVLHekc4MVvfN6oPzqYrYiUBwz4rf4Qr8Bxa5PZ9L8K+kq52T8k6ryOyulW0gl+Ho3mIwb7VKwrYqbHzXCZ7afMevV9mqXM55Vv8CEQjiyaXu6iAgcreyA73mn8XjRkKYSBp5zY7dM2GIqmcJywTm7s8QlyizQTA8gdg3U1aw/xXUo/TwbbR+LSB3MZ72qSVM+UJQWb0trPTLoH8+9UocFKtGAWo/kLiPHwfQVivOh+JT/NBnOAympHQ+D4jdlDcehUzChEbWDVq0mYEAVTCqLg92QiYHwLRhvpiNmbhWy6IlFTUDX1YEI3dwr2RLX2lY0Dw7vp27O4e+2SKJoiehWk0qdPiKAB16/hyya1ZgHH0a5nN+Z1OCfCfpURW/6RetWC+d03GrH2IovJLoM64OyD1GvokypcQJR1LRsH2BsTOqi4heL9MXYyg+uQUBo4oajBiUAO/K34tTShAwEfyvoXTvGsDgutPo+iClB5kTWbtSMW5s5s+ZIxo=
  on:
    tags: true
    repo: OneLittleRobot/resistor-data
    branch: master



